# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package*.json ./
RUN npm install --ignore-scripts

# Bundle app source
COPY . .

# Build the TypeScript code
RUN npm run build

# Expose a port if necessary (optional)

# Start the MCP server
CMD [ "node", "dist/index.js" ]
